version: "3.8"
services:
  backend:
    build: ./TasksAPI
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cicd_database
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  frontend:
    build: ./TasksClient
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:14.9
    environment:
      POSTGRES_DB: cicd_database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d cicd_database"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
      
